package lt.debarz.reviewservice.model;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

import java.util.ArrayList;
import java.util.List;

/**
 * A Review document.
 */
@AllArgsConstructor
@NoArgsConstructor
@Data
@Document(collection = "Reviews")
public class Review {
    /**
     * The ID, or primary key, of the Review, as generated by MongoDB.
     */
    private String id;

    /**
     * The product ID for which this review is applicable.
     */
    private Integer productId;

    /**
     * The version of the review, which is an increasing number starting with 1.
     */
    private Integer version = 1;

    /**
     * A list of review entries - these contain user reviews of the product.
     */
    private List<ReviewEntry> entries = new ArrayList<>();

    public Review(Integer productId) {
        this.productId = productId;
    }

    public Review(String id, Integer productId) {
        this.id = id;
        this.productId = productId;
    }

    public Review(String id, Integer productId, Integer version) {
        this.id = id;
        this.productId = productId;
        this.version = version;
    }

    public Review(Integer productId, Integer version) {
        this.productId = productId;
        this.version = version;
    }
}
